#!/usr/bin/env bash
# Single-pass Google Takeout import via immich-go. Run inside tmux/screen.
set -euo pipefail

API="http://localhost:2283"
KEY_FILE="/Users/szelenin/immich-data/api-key.txt"
TAKEOUT_GLOB="/Volumes/HomeRAID/google-takeout/takeout-20260403T195541Z-3-*.zip"
LOG_FILE="/Users/szelenin/immich-data/immich-go.log"
if [[ ! -f "$KEY_FILE" ]]; then
  echo "API key not found at $KEY_FILE" >&2
  exit 1
fi

KEY=$(cat "$KEY_FILE")
zip_count=$(ls $TAKEOUT_GLOB 2>/dev/null | wc -l | tr -d ' ')
if [[ "$zip_count" != "49" ]]; then
  echo "Expected 49 photo-data zips matching $TAKEOUT_GLOB, found $zip_count" >&2
  exit 1
fi

if ! command -v immich-go >/dev/null; then
  echo "immich-go not found on PATH. Install with: brew install immich-go" >&2
  exit 1
fi

echo "Starting immich-go import:"
echo "  zips:        $zip_count"
echo "  log-file:    $LOG_FILE"
echo "  session-tag: auto-generated by immich-go (--session-tag is boolean in v0.31)"
echo "Hit Ctrl-C in the next 5 seconds to abort."
sleep 5

# immich-go 0.31.0 vs the original plan:
# - --session-tag is a boolean (no value); auto-generates "{immich-go}/YYYY-MM-DD HH-MM-SS"
# - --pause-immich-jobs is also boolean; default is true so passing the flag bare is fine
# - --no-ui added so the TUI doesn't try to render to a non-tty (we run from nohup)
immich-go upload from-google-photos \
  --server="$API" \
  --api-key="$KEY" \
  --concurrent-tasks=4 \
  --client-timeout=60m \
  --pause-immich-jobs \
  --on-errors=continue \
  --session-tag \
  --no-ui \
  --log-file="$LOG_FILE" \
  $TAKEOUT_GLOB

echo "immich-go finished. Resume Immich jobs via admin UI:"
echo "  http://localhost:2283 → Administration → Jobs → 'Resume All'"
echo "Or via API (load API key from $KEY_FILE first):"
echo "  curl -X PUT -H \"x-api-key: \$KEY\" '$API/api/jobs/<queue>/resume' (per queue)"
